version: "3.8"

x-common-variables: &common-variables
  KONG_DATABASE: postgres
  KONG_PG_DATABASE: kong
  KONG_PG_HOST: kong-db
  KONG_PG_USER: konguser
  KONG_PG_PASSWORD: konguser

services:
  keycloak:
    image: jboss/keycloak:11.0.3
    container_name: keycloak
    hostname: keycloak
    depends_on:
      - kong-db
    command:
      [
        "-b",
        "0.0.0.0",
        "-Djboss.socket.binding.port-offset=1000",
        "-Dkeycloak.migration.action=import",
        "-Dkeycloak.migration.provider=singleFile",
        "-Dkeycloak.migration.file=/tmp/realm-config/master-realm.json",
        "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING",
        "-Dkeycloak.profile.feature.upload_scripts=enabled",
      ]
    ports:
      - 9080:9080/tcp
    volumes:
      - ./local/keycloak/master-realm.json:/tmp/realm-config/master-realm.json
    networks:
      keycloak:
        aliases:
          - keycloak.localtest.me
      kong-net: {}
