version: "3.8"

services:
  keycloak:
    image: jboss/keycloak:11.0.3
    container_name: keycloak
    hostname: keycloak
    command:
      [
        "-b",
        "0.0.0.0",
        "-Djboss.socket.binding.port-offset=1000",
        "-Dkeycloak.migration.action=import",
        "-Dkeycloak.migration.provider=singleFile",
        "-Dkeycloak.migration.file=/tmp/realm-config/master-realm.json",
        "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING",
        "-Dkeycloak.profile.feature.upload_scripts=enabled",
      ]
    ports:
      - 9080:9080/tcp
    volumes:
      - /__w/test-docker-compose/test-docker-compose/local/keycloak/master-realm.json:/tmp/realm-config/master-realm.json
