name: Build and Deploy Cypress and Execute Tests

on:
  push:
    branches:
      - "dev"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: lucasalt/act_base:latest
      options: -u root -w /app
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - uses: actions/checkout@v1
      - name: Spin up API Services Portal and Run E2E Tests
        run: |
          ls -lrta
