name: Build and Deploy Cypress and Execute Tests

on:
  push:
    branches:
      - "never"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Spin up API Services Portal and Run E2E Tests
        run: |
          docker-compose up
