name: Create Pull Request

on:
  push:
    branches:
      - test

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Reset main branch
        run: |
          git fetch origin test:test

      # Make changes to pull request here

      - name: Create Pull Request for Release
        uses: peter-evans/create-pull-request@v4
