name: Create Pull Request

on:
  push:
    branches:
      - test

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Create Latest Release',
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'main',
              body: [
                'This Pull Request is auto-created by [actions/github-script](https://github.com/actions/github-script).',
                'Please update this PR with appropriate labels to target specific type of release'
              ].join('\n'),
              draft: true
            });
