name: Create Issue

on:
  push:
    branches: ["main"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Parse JSON and Create Issue
        run: |
          FAILURE_COUNT=$(cat e2e/results/bcgov-aps-e2e-report.json | jq '.stats.failures')
          if [[ "$FAILURE_COUNT" -gt 0 ]]; then
            echo "Hello, the failure count is $FAILURE_COUNT"
          fi
